include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    prefer_for_elements_to_map_fromiterable: ignore
  exclude:
    - "**.mocks.dart"
    - "**.g.dart"
    - "**.freezed.dart"
    - "lib/generated/**"